In [2]:
import sklearn.metrics as skmet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.model_selection as sksel
import sklearn.preprocessing as skprepro
import sklearn.linear_model as skmod

In [3]:
hours_homework = [1, 10, 3, 20, 32, 6, 1, 9, 2, 10, 5]
sucess_exam = ['fail', 'pass','fail','pass','pass','fail','fail','pass','fail', 'fail', 'pass']

In [4]:
pass_not = []
for i in sucess_exam:
    if i == 'fail':
        pass_not.append(0)
    else :
        pass_not.append(1)

In [5]:
hours_homework = np.array(hours_homework).reshape(-1,1)
pass_not = np.array(pass_not)

In [8]:
model = skmod.LogisticRegression()
model = model.fit(hours_homework, pass_not)

In [16]:
print(model.predict_proba(np.array([[8]])))

[[0.47363896 0.52636104]]


In [17]:
Salary = [3.19, 4.28, 2.63, 4.6, 1.26, 1.17, 2.58, 4.19, 0.67, 1.88, 3.81, 1.57, 2.44, 0.97, 3.59, 1.7, 1.34, 1.91, 2.77, 2.53, 1.27]
Age= [52, 66, 56, 50, 29, 20, 36, 33, 45, 53, 24, 59, 45, 69, 68, 26, 43, 45, 61, 20, 53]
Car = ["Mercedes", "Mercedes", "Mercedes", "Toyota", "Kia", "Kia", "Toyota", "Toyota", "Peugot", "Toyota", "Peugot", "Toyota", "Toyota", "Peugot", "Mercedes", "Kia", "Toyota", "Toyota", "Mercedes", "Peugot", "Toyota"]

In [18]:
encoder = skprepro.LabelEncoder()
fav_code = encoder.fit_transform(Car)
print(fav_code)

[1 1 1 3 0 0 3 3 2 3 2 3 3 2 1 0 3 3 1 2 3]


In [21]:
age = np.array(Age).reshape(-1,1)
sal = np.array(Salary).reshape(-1,1)
x = np.hstack([age,sal])
fav_code = np.array(fav_code)

In [22]:
model = skmod.LogisticRegression(multi_class = 'ovr')
model = model.fit(x, fav_code)

In [33]:
predict_proba = model.predict_proba(np.array([[45, 2.5]]))
print(predict_proba)
print(encoder.classes_)

[[0.01833553 0.10300613 0.25121112 0.62744722]]
['Kia' 'Mercedes' 'Peugot' 'Toyota']
