In [1]:
import numpy as np
import sklearn.linear_model as skmod
import sklearn.preprocessing as skprepro
import sklearn.model_selection as sksel
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
file = pd.read_parquet(r"Downloads\Data_to_analyse.parquet")

In [4]:
print(file)

     Account_money  Age  Money_given
0         59781878   81   569.984834
1         72742895   39   812.686814
2         22068382   34   758.240188
3         42234777   69   694.674949
4         74637447   21   965.911727
..             ...  ...          ...
995       85403167   44   808.895932
996       16766354   20   816.391936
997       96516749   45   949.277095
998       40368947   80   635.242943
999       33795363   74   624.205544

[1000 rows x 3 columns]


In [5]:
x1 = file["Age"].to_numpy().reshape(-1, 1)
x2 = file["Account_money"].to_numpy().reshape(-1, 1)
y1 = file["Money_given"].to_numpy().reshape(-1, 1)
x = np.hstack([x1, x2])

In [6]:
print(x)

[[      81 59781878]
 [      39 72742895]
 [      34 22068382]
 ...
 [      45 96516749]
 [      80 40368947]
 [      74 33795363]]


In [7]:
data_x_train, data_x_test, data_y_train, data_y_test =sksel.train_test_split(x, y1, train_size = 0.8,shuffle = True)

# plt.scatter(data_x_train, data_y_train)
# plt.scatter(data_x_test, data_y_test)

In [8]:
stanScaler = skprepro.StandardScaler()

In [9]:
stan1 = stanScaler.fit_transform(data_x_train)
labelScaler = skprepro.StandardScaler()
label_stan = labelScaler.fit_transform(data_y_train)
print(stan1)


[[-1.65413852  1.09938397]
 [ 0.3622789   0.91234451]
 [-1.60495761 -0.57131673]
 ...
 [ 0.65736437  1.59996722]
 [-1.65413852 -0.7851711 ]
 [ 1.44425898  1.64148554]]


In [10]:
print(label_stan)

[[ 2.13900447e+00]
 [ 1.50311822e-01]
 [ 1.85192356e+00]
 [-1.62106218e+00]
 [ 1.30590983e+00]
 [-8.69271426e-01]
 [ 8.68228858e-01]
 [-3.98408442e-01]
 [-5.58971303e-01]
 [-2.07876276e-01]
 [ 1.55393153e+00]
 [-8.09753376e-01]
 [-1.10061332e+00]
 [ 1.05612122e+00]
 [-2.48387662e-01]
 [-2.60876599e-01]
 [-1.68570621e+00]
 [-4.59166627e-01]
 [-7.22543813e-01]
 [-6.67855682e-01]
 [-2.79545132e-01]
 [ 1.54290839e+00]
 [ 5.13544058e-01]
 [ 1.04518787e+00]
 [ 1.21930407e+00]
 [-3.49580810e-01]
 [ 9.46372992e-01]
 [-2.65393996e-01]
 [ 1.62390979e+00]
 [-5.61374161e-01]
 [ 1.41202939e+00]
 [ 7.63112091e-01]
 [ 1.03906495e+00]
 [ 5.84169676e-01]
 [ 2.11758123e+00]
 [-5.91403217e-01]
 [-8.98207243e-01]
 [ 5.67300763e-01]
 [ 1.36848434e+00]
 [-6.00168162e-01]
 [-6.16855141e-01]
 [-5.30826546e-01]
 [-1.13741546e+00]
 [-4.45800986e-01]
 [ 1.40130079e+00]
 [-6.79638758e-01]
 [-7.37464682e-01]
 [-6.13209054e-01]
 [-1.11351884e+00]
 [-1.46439111e+00]
 [ 8.25747499e-01]
 [-1.20842677e+00]
 [ 5.2234718

In [11]:
model = skmod.LinearRegression().fit(stan1, label_stan)

In [12]:
print(model.coef_)
print(model.intercept_)
print(model.score(stan1, label_stan))
#y' = (-0.860)*x1  +  0.353 * x2 + (-2.57400011e-17)

[[-0.87879643  0.36331381]]
[2.37850979e-16]
0.8722116792025962


In [13]:
stanScaler = skprepro.StandardScaler()

In [14]:
stan1 = stanScaler.fit_transform(data_x_test)
labelScaler = skprepro.StandardScaler()
label_stan = labelScaler.fit_transform(data_y_test)

In [15]:
model = skmod.LinearRegression().fit(stan1, label_stan)

In [16]:
print(model.coef_)
print(model.intercept_)
print(model.score(stan1, label_stan))
# y' = (-0.836) * x1 + 0.327 * x2 + (-4.320)

[[-0.83610952  0.32779202]]
[-4.32076425e-16]
0.8744692171903712
