In [61]:
import numpy as np
import sklearn.linear_model as skmod
import sklearn.preprocessing as skprepro
import pandas as pd

In [62]:
df = pd.read_parquet(r"Downloads\data_streamers.parquet")

In [63]:
print(df)

    Time_of_the_day  Number_of_viewers  Average_age_of_viewers  \
0                10              23811                      20   
1                11              47309                      16   
2                 1              25461                      30   
3                14               9719                      29   
4                 2              30176                      14   
5                14               5560                      21   
6                 9              45401                       7   
7                 5              43503                      27   
8                 5              40367                      22   
9                 9              20385                      15   
10                0              26368                      28   
11                6               2429                      27   
12                6              29969                      27   
13               23              37973                      17   
14        

In [64]:
feat1 = df["Time_of_the_day"].to_numpy().reshape(-1,1)
feat2 = df["Number_of_viewers"].to_numpy().reshape(-1,1)
feat3 = df["Average_age_of_viewers"].to_numpy().reshape(-1,1)
feat = np.hstack([feat1, feat2, feat3])
print(feat)
label = df["Video_game"].to_numpy()
print(label)
encoder = skprepro.LabelEncoder()
label = encoder.fit_transform(label)

[[   10 23811    20]
 [   11 47309    16]
 [    1 25461    30]
 [   14  9719    29]
 [    2 30176    14]
 [   14  5560    21]
 [    9 45401     7]
 [    5 43503    27]
 [    5 40367    22]
 [    9 20385    15]
 [    0 26368    28]
 [    6  2429    27]
 [    6 29969    27]
 [   23 37973    17]
 [   19 17662    12]
 [   19 37070    28]
 [   19  5146    26]
 [    2 47057    11]
 [    4  1423    19]
 [   19 46764     7]
 [    2 25286    25]
 [   18 46267    17]
 [    4  4617    26]
 [   15  9894    24]
 [   12 14649    23]
 [   22  2477    27]
 [   12 16949    30]
 [    4 47644    15]
 [    7  4693    13]]
['League of Legend' 'Fifa' 'Minecraft' 'Minecraft' 'Fifa'
 'League of Legend' 'GTA V' 'League of Legend' 'League of Legend'
 'League of Legend' 'Minecraft' 'Minecraft' 'Minecraft' 'Fifa' 'Fifa'
 'League of Legend' 'Minecraft' 'Fifa' 'Minecraft' 'GTA V' 'Minecraft'
 'Fifa' 'Minecraft' 'League of Legend' 'League of Legend' 'Minecraft'
 'Minecraft' 'Fifa' 'League of Legend']


In [65]:
model = skmod.LogisticRegression(multi_class = 'ovr')
model = model.fit(feat, label)

In [66]:
predict_proba1 = model.predict(np.array([[11, 10000, 18]]))
print(predict_proba1)
print(encoder.classes_[predict_proba1][0])

[2]
League of Legend


In [67]:
predict_proba2 = model.predict_proba(np.array([[23, 1000, 30]]))
print(predict_proba2)
print(encoder.classes_)

[[1.09953053e-02 1.10048111e-09 3.36041953e-01 6.52962741e-01]]
['Fifa' 'GTA V' 'League of Legend' 'Minecraft']


In [68]:
import sklearn.model_selection as sksel

In [69]:
data_x_train, data_x_test, data_y_train, data_y_test =sksel.train_test_split(feat, label, train_size = 0.8,shuffle = True)

In [75]:
model = skmod.LogisticRegression(multi_class = 'ovr')
model = model.fit(data_x_train, data_y_train)

In [76]:
predict_proba1 = model.predict(np.array([[11, 10000, 18]]))
print(predict_proba1)
print(encoder.classes_[predict_proba1][0])

[2]
League of Legend


In [77]:
predict_proba2 = model.predict_proba(np.array([[23, 1000, 30]]))
print(predict_proba2)
print(encoder.classes_)

[[4.99293238e-03 1.59792771e-09 3.46508787e-01 6.48498279e-01]]
['Fifa' 'GTA V' 'League of Legend' 'Minecraft']


In [78]:
model = skmod.LogisticRegression(multi_class = 'ovr')
model = model.fit(data_x_test, data_y_test)

In [83]:
predict_proba1 = model.predict(np.array([[11, 10000, 18]]))
print(predict_proba1)
print(encoder.classes_[predict_proba1][0])

[2]
League of Legend


In [80]:
predict_proba2 = model.predict_proba(np.array([[23, 1000, 30]]))
print(predict_proba2)
print(encoder.classes_)

[[1.09335820e-04 2.63256353e-01 7.36634311e-01]]
['Fifa' 'GTA V' 'League of Legend' 'Minecraft']
